[env:uno]
platform = atmelavr
board = uno
framework = arduino

build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -I ../shared/include
  -Os

lib_deps =

lib_ldf_mode = deep+

monitor_speed = 57600
upload_speed  = 115200
